config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  resources :random_things
  root 'random_things#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

app/models/random_thing.rb
class RandomThing < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :get_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments = Comment.all
    @comment = Comment.new
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def create
  end

  private

  def get_comment
    @comment = Comment.find(params[:id])
  end

end

app/controllers/random_things_controller.rb
class RandomThingsController < ApplicationController
  before_action :get_random_thing, only: [:show, :edit, :update, :destroy]

  def index
    @random_things = RandomThing.all
  end

  def show
  end

  def new
    @random_thing = RandomThing.new
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def create
  end

  private

  def get_random_thing
    @random_thing = RandomThing.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/random_things_helper.rb
module RandomThingsHelper
end

app/views/comments/_comment.html.erb
<div class="card">
  <div class="card-body">
    <p><%= comment.body %><p>
    <em><%= "by - #{comment.user.email}" %></em>
  </div>
</div>

app/views/comments/index.html.erb
<H1>you are now on the comments page</H1>
<%= form_for @comment, url: '#' do |f| %>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>

  <%= f.submit "Post", class: 'btn btn-primary btn-lg' %>
<% end %>

<div id="comments">
  <%= render @comments %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Action</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/random_things/index.html.erb
<%= @random_things.inspect %>

app/views/shared/_nav.html.erb
<h1>This is the shared nav</h1>
<%= link_to "LOGIN", new_user_session_path %>
<%= link_to "logout", destroy_user_session_path %>
<%= link_to "Comments", comments_path %>
<%= link_to "Random Things", root_path %>